#include <iostream>
#include <fstream>
#include <string>
#include <cassert>
#include <cstdlib>
#include <math.h>
#include <time.h>
#include <sstream>
#include <cstring>
#include "coordstructs.h"
#include "linkedlist.h"
#include "normalscalculation.h"
#include "vectorparser.h"
#include "builddrawlist.h"
#include "drawirregularpoly.h"
#include "status.h"
#include "vehicletools.h"
#include "controllerinterface.h"
#include "buildroadlineslist.h"
#include "drawroadlines.h"
#include "memblockparser.h"
#include "textpopupcontroller.h"
#include "eventlog.h"